export const ACTION_TYPES = {
  DATE_INPUT: "DATE_INPUT",
  TIME_FROM_INPUT: "TIME_FROM_INPUT",
  TIME_TO_INPUT: "TIME_TO_INPUT",
  FIXED_TIME_INPUT: "FIXED_TIME_INPUT",
  LOADING_ADDRESS_INPUT: "LOADING_ADDRESS_INPUT",
  POST_CODE_INPUT: "POST_CODE_INPUT",
  COUNTRY_INPUT: "COUNTRY_INPUT",
  DISTANCE_INPUT: "DISTANCE_INPUT",
  COORDINATES_INPUT: "COORDINATES_INPUT",
  CARGO_INPUT: "CARGO_INPUT",
  REF_INPUT: "REF_INPUT",
};
