export const ACTION_TYPES = {
  LOADING_INPUT: "LOADING_INPUT",
  ADD_LOADING: "ADD_LOADING",
  REMOVE_LOADING: "REMOVE_LOADING",
  ADD_UNLOADING: "ADD_UNLOADING",
  REMOVE_UNLOADING: "REMOVE_UNLOADING",
  UNLOADING_INPUT: "UNLOADING_INPUT",
};
